name: Publish NuGet Package

on:
  push:
    tags:
      - 'v*'

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: |
            6.0.x
            8.0.x
            9.0.x
      
      - name: Extract version from tag
        id: get_version
        run: |
          VERSION=${GITHUB_REF#refs/tags/v}
          echo "Extracted version: $VERSION"
          echo "VERSION=$VERSION" >> $GITHUB_OUTPUT
      
      - name: Build and pack
        run: |
          # We don't need to specify PackageId here as it's in the project file
          dotnet build src/Blake2Fast/Blake2Fast.csproj -c Release -p:Version=${{ steps.get_version.outputs.VERSION }}
          dotnet pack src/Blake2Fast/Blake2Fast.csproj -c Release -p:Version=${{ steps.get_version.outputs.VERSION }} --output nuget-packages
      
      - name: Run tests
        run: dotnet test tests/Blake.Test -c Release
      
      - name: Push to NuGet
        run: dotnet nuget push nuget-packages/*.nupkg --api-key ${{ secrets.NUGET_API_KEY }} --source https://api.nuget.org/v3/index.json